/*
 * This file was automatically generated by EvoSuite
 * Wed May 26 01:40:53 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.AssumptionViolatedException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestProgram_ESTest extends TestProgram_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestProgram testProgram0 = new TestProgram();
      int[] intArray0 = new int[11];
      intArray0[5] = 5007;
      // Undeclared exception!
      try { 
        testProgram0.TestStudentSubmission(intArray0);
        fail("Expecting exception: AssumptionViolatedException");
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
         verifyException("org.junit.Assume", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestProgram testProgram0 = new TestProgram();
      int[] intArray0 = new int[2];
      intArray0[0] = 115;
      boolean boolean0 = testProgram0.elementsSame(intArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestProgram testProgram0 = new TestProgram();
      int[] intArray0 = new int[2];
      boolean boolean0 = testProgram0.elementsSame(intArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[0];
      TestProgram testProgram0 = new TestProgram();
      boolean boolean0 = testProgram0.elementsSame(intArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TestProgram testProgram0 = new TestProgram();
      boolean boolean0 = testProgram0.elementsSame((int[]) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TestProgram testProgram0 = new TestProgram();
      int[] intArray0 = new int[11];
      testProgram0.TestStudentSubmission(intArray0);
      assertEquals(11, intArray0.length);
  }
}
